name: Pull Request Check
on: [pull_request]

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: "json"

      - name: Running unit test
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.2
          php_extensions: "json"
          args: "-d date.timezone=Europe/Budapest"
          memory_limit: 300M
          configuration: phpunit.xml.dist
          testsuite: unittest
